name: test
on: [workflow_dispatch]

jobs:
  
  test:
    name: test
    runs-on: ubuntu-latest
    steps:    
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2      
      with:
        name: latest-model
        workflow: register_model.yml
        #workflow_conclusion: success        
    - run: |
        ls
        cat latest-model.txt